# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name : Skill
    url : skill/
    weight : 100
  - name : Language
    url : skill/language/
    pageRef : skill/laguage
    weight : 101
    parent : Skill
  - name : Framework
    url : skill/framework/
    pageRef : skill/framework
    weight : 102
    parent : Skill

  - name: Projects
    url: projects/
    weight: 200
  - name: Front_Project
    url: project/FrontEnd/
    pageRef : project/FrontEnd
    weight: 201
    parent: Projects
  - name: Linux_Project
    url: project/Linux/
    pageRef : project/Linux
    weight: 202
    parent: Projects
  - name: Python_Project
    url: project/Python/
    pageRef : project/Python
    weight: 203
    parent: Projects

  - name: Study Record
    url: study/
    weight: 300
  - name: Front
    url: study/Front/
    pageRef : study/Front
    weight: 301
    parent: Study Record
  - name: ML/DL
    url: study/ML_DL/
    pageRef : study/ML_DL
    weight: 302
    parent: Study Record
  - name: React
    url: study/react/
    pageRef : study/react
    weight: 303
    parent: Study Record

  - name : Thesis
    url : read
    pageRef: read
    weight : 400
  - name : Read
    url : read
    pageRef: read
    weight : 401
    parent : Thesis
  - name : Write
    url : write
    pageRef: write
    weight : 402
    parent : Thesis

  - name : Grade
    url : grade/
    weight : 500
  - name : AnimalBiotech
    url : grade/animal/
    pageRef : grade/animal
    weight : 501
    parent : Grade
  - name : ConputerScience
    url : grade/computer/
    pageRef : grade/computer
    weight : 502
    parent : Grade
  
  
  


  