# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name : Skill
    url : skill/
    weight : 10
  - name : Language
    url : skill/language/
    pageRef : skill/laguage
    weight : 1
    parent : Skill
  - name : Framework
    url : skill/framework/
    pageRef : skill/framework
    weight : 2
    parent : Skill

  - name: Projects
    url: projects/
    weight: 11
  - name: Front_Project
    url: project/FrontEnd/
    pageRef : project/FrontEnd
    weight: 1
    parent: Projects
  - name: Linux_Project
    url: project/Linux/
    pageRef : project/Linux
    weight: 2
    parent: Projects

  - name: Study Record
    url: study/
    weight: 12
  - name: Front
    url: study/Front/
    pageRef : study/Front
    weight: 1
    parent: Study Record
  - name: ML/DL
    url: study/ML_DL/
    pageRef : study/ML_DL
    weight: 2
    parent: Study Record
  - name: React
    url: study/react/
    pageRef : study/react
    weight: 3
    parent: Study Record
  
  - name : Grade
    url : grade/
    weight : 30
  - name : AnimalBiotech
    url : grade/animal/
    pageRef : grade/animal
    weight : 1
    parent : Grade
  - name : ConputerScience
    url : grade/computer/
    pageRef : grade/computer
    weight : 2
    parent : Grade
  
  - name : Thesis
    url : thesis/
    weight : 20
  - name : Read
    url : thesis/read/
    pageRef : thesis/read
    weight : 1
    parent : Thesis
  - name : Write
    url : thesis/write/
    pageRef : thesis/write
    weight : 2
    parent : Thesis
  
  


  