main:
  - name: Bio
    weight : 1
    url: bio
    pageRef: bio

  - name : Skill
    weight : 100
  - name : Language
    url : skill/language/
    pageRef : skill/laguage
    weight : 101
    parent : Skill
  - name : Framework
    url : frameworks/
    pageRef : frameworks/
    weight : 102
    parent : Skill

  - name: Projects
    weight: 200
  - name: Front_Project
    url: project/FrontEnd/
    pageRef : project/FrontEnd
    weight: 201
    parent: Projects
  - name: Linux_Project
    url: project/Linux/
    pageRef : project/Linux
    weight: 202
    parent: Projects
  - name: Python_Project
    url: project/Python/
    pageRef : project/Python
    weight: 203
    parent: Projects

  - name: Study Record
    weight: 300
  - name: Front
    url: study/Front/
    pageRef : study/Front
    weight: 301
    parent: Study Record
  - name: ML/DL
    url: study/ML_DL/
    pageRef : study/ML_DL
    weight: 302
    parent: Study Record
  - name: React
    url: study/react/
    pageRef : study/react
    weight: 303
    parent: Study Record

  - name : Thesis
    weight : 400
  - name : Read
    url : read
    pageRef: read
    weight : 401
    parent : Thesis
  - name : Write
    url : write
    pageRef: write
    weight : 402
    parent : Thesis

  - name : Grade
    weight : 500
  - name : AnimalBiotech
    url : animalbiotech
    pageRef : animalbiotech
    weight : 501
    parent : Grade
  - name : ConputerScience
    url : computerscience
    pageRef : computerscience
    weight : 502
    parent : Grade
